[project]
name = "trial-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.2.0",
    "scikit-learn>=1.6.0",
    "torch>=2.5.1",
]
